module.exports = [
  { id: 1, title: 'Snapback', color: 'red', category: 'hats', price: 10 },
  { id: 5, title: 'Jacket', color: 'black', category: 'jackets', price: 15 },
  { id: 19, title: 'T-Shirt', color: 'orange', category: 'shirts', price: 10 },
  { id: 10, title: 'Beanie', color: 'black', category: 'hats', price: 7 },
  { id: 2, title: 'Snapback', color: 'blue', category: 'hats', price: 10 },
  { id: 31, title: 'Shorts', color: 'orange', category: 'shorts', price: 15 },
  { id: 3, title: 'Snapback', color: 'green', category: 'hats', price: 10 },
  { id: 11, title: 'Sweater', color: 'black', category: 'sweaters', price: 12 },
  { id: 4, title: 'Snapback', color: 'orange', category: 'hats', price: 10 },
  { id: 18, title: 'T-Shirt', color: 'green', category: 'shirts', price: 10 },
  { id: 23, title: 'Pants', color: 'green', category: 'pants', price: 15 },
  { id: 13, title: 'Sweater', color: 'blue', category: 'sweaters', price: 12 },
  { id: 6, title: 'Jacket', color: 'red', category: 'jackets', price: 15 },
  { id: 0, title: 'Snapback', color: 'black', category: 'hats', price: 10 },
  { id: 15, title: 'Beanie', color: 'red', category: 'hats', price: 7 },
  { id: 14, title: 'Beanie', color: 'orange', category: 'hats', price: 7 },
  { id: 25, title: 'Pants', color: 'blue', category: 'pants', price: 15 },
  { id: 16, title: 'Sweater', color: 'green', category: 'sweaters', price: 12 },
  { id: 28, title: 'Shorts', color: 'green', category: 'shorts', price: 15 },
  { id: 17, title: 'Sweater', color: 'green', category: 'sweaters', price: 12 },
  { id: 20, title: 'T-Shirt', color: 'blue', category: 'shirts', price: 10 },
  { id: 21, title: 'Beanie', color: 'green', category: 'hats', price: 7 },
  { id: 32, title: 'Shorts', color: 'blue', category: 'shorts', price: 15 },
  { id: 7, title: 'Jacket', color: 'blue', category: 'jackets', price: 15 },
  { id: 33, title: 'T-Shirt', color: 'red', category: 'shirts', price: 10 },
  {
    id: 22,
    title: 'Sweater',
    color: 'orange',
    category: 'sweaters',
    price: 12
  },
  { id: 8, title: 'Jacket', color: 'green', category: 'jackets', price: 15 },
  { id: 26, title: 'Pants', color: 'black', category: 'pants', price: 15 },
  { id: 9, title: 'Jacket', color: 'orange', category: 'jackets', price: 15 },
  { id: 12, title: 'Beanie', color: 'blue', category: 'hats', price: 7 },
  { id: 29, title: 'Shorts', color: 'red', category: 'shorts', price: 15 },
  { id: 34, title: 'Pants', color: 'red', category: 'pants', price: 15 },
  { id: 24, title: 'T-Shirt', color: 'blue', category: 'shirts', price: 10 },
  { id: 35, title: 'Pants', color: 'orange', category: 'pants', price: 15 },
  { id: 30, title: 'Shorts', color: 'black', category: 'shorts', price: 15 }
];
